<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Procurement;
use Illuminate\Support\Facades\Schema;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        User::truncate();
        Procurement::truncate();
        Schema::enableForeignKeyConstraints();

        // 1. Create Admin
        User::create([
            'name' => 'Admin KMI',
            'email' => 'admin@outlook.com',
            'password' => bcrypt('adminkmi123'),
        ]);

        // 2. Bulk Create Dummy Data from PDF
        $procurements = [
            [
                'kode_pengadaan' => '1000003892',
                'nama_barang' => 'IT Peripheral',
                'vendor' => 'PT Alpha Cipta',
                'tanggal_in' => '2025-04-23',
                'tanggal_out' => '2025-05-27',
                'tanggal_te' => '2025-05-27',
                'tanggal_rete' => null,
                'tanggal_po' => '2025-06-16',
            ],
            [
                'kode_pengadaan' => '1000003895',
                'nama_barang' => 'Asus zen book for SM',
                'vendor' => 'PT Technology Solustion Indo',
                'tanggal_in' => '2025-04-23',
                'tanggal_out' => '2025-05-27',
                'tanggal_te' => '2025-05-19',
                'tanggal_rete' => '2025-05-27',
                'tanggal_po' => '2025-06-16',
            ],
            [
                'kode_pengadaan' => '1000003896',
                'nama_barang' => 'Microsoft Surface for DPGM',
                'vendor' => 'PT Alpha Cipta',
                'tanggal_in' => '2025-04-23',
                'tanggal_out' => '2025-05-27',
                'tanggal_te' => '2025-05-19',
                'tanggal_rete' => '2025-05-26',
                'tanggal_po' => '2025-06-16',
            ],
            [
                'kode_pengadaan' => '4000001763',
                'nama_barang' => 'Renewal Autocad',
                'vendor' => 'PT Pacific Citra Mandiri',
                'tanggal_in' => '2025-04-16',
                'tanggal_out' => '2025-05-26',
                'tanggal_te' => '2025-05-22',
                'tanggal_rete' => null,
                'tanggal_po' => '2025-06-16',
            ],
            [
                'kode_pengadaan' => '1000003915',
                'nama_barang' => 'Microsoft Surface for COMUT',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2025-05-08',
                'tanggal_out' => '2025-05-23',
                'tanggal_te' => '2025-05-23',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000001812',
                'nama_barang' => 'Windows 11 Pro Volume GGWA',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2025-05-21',
                'tanggal_out' => '2025-07-02',
                'tanggal_te' => '2025-07-01',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000001815',
                'nama_barang' => 'Sectigo SSL 1 Year and Installation',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2025-05-23',
                'tanggal_out' => '2025-05-26',
                'tanggal_te' => '2025-05-26',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '1000003941',
                'nama_barang' => 'Installation CCTV ExploProof and Indoor',
                'vendor' => 'CV Tigatra Adikara',
                'tanggal_in' => '2025-05-27',
                'tanggal_out' => '2025-07-21',
                'tanggal_te' => '2025-06-23',
                'tanggal_rete' => null,
                'tanggal_po' => '2025-08-25',
            ],
            [
                'kode_pengadaan' => '4000001822',
                'nama_barang' => 'Client Cert for SSL VPN',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2025-05-28',
                'tanggal_out' => null,
                'tanggal_te' => null,
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000001762',
                'nama_barang' => '1 Year Renewal Baracuda',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2025-04-16',
                'tanggal_out' => null,
                'tanggal_te' => null,
                'tanggal_rete' => '2025-05-30',
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000001824',
                'nama_barang' => 'Renewal Microsoft 365 Business',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2025-06-02',
                'tanggal_out' => '2025-07-02',
                'tanggal_te' => '2025-07-01',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000001832',
                'nama_barang' => 'Renewal License Cisco Catalyst 9200L-48T',
                'vendor' => 'PT KDDI Indonesia',
                'tanggal_in' => '2025-06-09',
                'tanggal_out' => '2025-06-25',
                'tanggal_te' => '2025-06-23',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000001835',
                'nama_barang' => 'Renewal License Fortigate Bontang-Jakarta',
                'vendor' => 'PT KDDI Indonesia',
                'tanggal_in' => '2025-06-10',
                'tanggal_out' => '2025-07-07',
                'tanggal_te' => '2025-06-23',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000001842',
                'nama_barang' => 'Maintenance & Update Core Website and CMS',
                'vendor' => 'PT Go Online Solusi',
                'tanggal_in' => '2025-06-18',
                'tanggal_out' => '2025-08-20',
                'tanggal_te' => '2025-07-11',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000001834',
                'nama_barang' => 'ISP ASTINET - WISTA',
                'vendor' => 'PT Telkom Indonesia',
                'tanggal_in' => '2025-06-10',
                'tanggal_out' => '2025-07-01',
                'tanggal_te' => '2025-06-30',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000001849',
                'nama_barang' => 'Renewal Microsoft Teams Pro Jakarta Office',
                'vendor' => 'PT KDDI Indonesia',
                'tanggal_in' => '2025-07-03',
                'tanggal_out' => '2025-07-07',
                'tanggal_te' => null,
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '1000003943',
                'nama_barang' => 'Access Control for Administration Building',
                'vendor' => 'CV Tigatra Adikara',
                'tanggal_in' => '2025-05-28',
                'tanggal_out' => '2025-12-03',
                'tanggal_te' => '2025-09-11',
                'tanggal_rete' => '2025-11-28',
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '1000004001',
                'nama_barang' => 'Printer-Scanner Peripheral',
                'vendor' => 'PT Technology Solustion Indo',
                'tanggal_in' => '2025-07-22',
                'tanggal_out' => '2025-08-14',
                'tanggal_te' => '2025-08-13',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '1000004005',
                'nama_barang' => 'IT Peripheral',
                'vendor' => 'PT Alpha Cipta',
                'tanggal_in' => '2025-07-23',
                'tanggal_out' => '2025-08-20',
                'tanggal_te' => '2025-08-19',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '1000004003',
                'nama_barang' => 'Visio dan Project License',
                'vendor' => 'PT Alpha Cipta Computindo',
                'tanggal_in' => '2025-07-29',
                'tanggal_out' => '2025-08-20',
                'tanggal_te' => '2025-08-19',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000001898',
                'nama_barang' => 'Microsoft Power BI Premium',
                'vendor' => 'PT Logos Teknologi Utama',
                'tanggal_in' => '2025-09-17',
                'tanggal_out' => '2025-09-24',
                'tanggal_te' => '2025-09-24',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '1000004062',
                'nama_barang' => 'Replace & Install SASHDD 02&05 Dell ME4024',
                'vendor' => 'PT KDDI Indonesia',
                'tanggal_in' => '2025-09-18',
                'tanggal_out' => '2025-10-17',
                'tanggal_te' => '2025-10-16',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000001901',
                'nama_barang' => 'Renewal License and Maintenance JKT Office',
                'vendor' => 'PT KDDI Indonesia',
                'tanggal_in' => '2025-09-19',
                'tanggal_out' => '2025-12-08',
                'tanggal_te' => '2025-10-27',
                'tanggal_rete' => '2025-12-04',
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000001910',
                'nama_barang' => 'Annual Maintenance Fortigate JKT and BTG',
                'vendor' => 'PT Alpha Cipta',
                'tanggal_in' => '2025-09-22',
                'tanggal_out' => '2025-10-02',
                'tanggal_te' => '2025-10-02',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '1000004102',
                'nama_barang' => 'ID Card Printer for Personnel',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2025-10-20',
                'tanggal_out' => '2025-11-13',
                'tanggal_te' => '2025-11-13',
                'tanggal_rete' => null,
                'tanggal_po' => '2025-12-10',
            ],
            [
                'kode_pengadaan' => '1000004114',
                'nama_barang' => 'Notebook Microsoft Surface Pro for PGM',
                'vendor' => 'PT Alpha Cipta Computindo',
                'tanggal_in' => '2025-11-05',
                'tanggal_out' => '2025-11-21',
                'tanggal_te' => '2025-11-17',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000001936',
                'nama_barang' => 'Renewal License Nextset SSO Browser',
                'vendor' => 'PT KDDI Indonesia',
                'tanggal_in' => '2025-11-05',
                'tanggal_out' => '2025-12-08',
                'tanggal_te' => '2025-11-25',
                'tanggal_rete' => '2025-12-05',
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000001959',
                'nama_barang' => 'Renewal 1Y VMWare and Veeam License',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2025-12-01',
                'tanggal_out' => null,
                'tanggal_te' => '2026-01-05',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000001961',
                'nama_barang' => 'Renewal License Cisco Catalyst 9200L-48T',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2025-12-09',
                'tanggal_out' => '2026-01-05',
                'tanggal_te' => '2026-01-29',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '1000004154',
                'nama_barang' => 'IT Peripheral',
                'vendor' => 'CV Tigatra Adikara',
                'tanggal_in' => '2025-12-09',
                'tanggal_out' => '2026-01-20',
                'tanggal_te' => '2026-01-08',
                'tanggal_rete' => '2026-01-19',
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '1000004178',
                'nama_barang' => 'PC Replacement for JKT Staff',
                'vendor' => 'CV Tigatra Adikara',
                'tanggal_in' => '2025-12-24',
                'tanggal_out' => '2026-01-15',
                'tanggal_te' => '2026-01-14',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '1000004175',
                'nama_barang' => 'IT Peripheral',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2025-12-23',
                'tanggal_out' => '2026-01-30',
                'tanggal_te' => '2026-01-29',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000001973',
                'nama_barang' => 'License Acronis JKT and Cisco BTG',
                'vendor' => '5000001309',
                'tanggal_in' => '2026-01-08',
                'tanggal_out' => '2026-03-02',
                'tanggal_te' => '2026-02-25',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000001988',
                'nama_barang' => 'Migration on-premise server to cloud',
                'vendor' => '5000001279',
                'tanggal_in' => '2026-01-21',
                'tanggal_out' => '2026-01-09',
                'tanggal_te' => '2026-01-03',
                'tanggal_rete' => '2026-01-09',
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000002004',
                'nama_barang' => 'MFA License for AD Server',
                'vendor' => 'PT KDDI Indonesia',
                'tanggal_in' => '2026-01-30',
                'tanggal_out' => '2026-02-25',
                'tanggal_te' => '2026-02-24',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000002010',
                'nama_barang' => 'FO PKT-KMI 3 core',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2026-01-05',
                'tanggal_out' => '2026-04-07',
                'tanggal_te' => '2026-04-02',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000002018',
                'nama_barang' => 'Dual Service Connectivity 100Mbps & Public 200Mbps',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2026-01-11',
                'tanggal_out' => '2026-03-11',
                'tanggal_te' => '2026-03-06',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000002017',
                'nama_barang' => 'Project FO Link to 7 location CCTV',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2026-01-10',
                'tanggal_out' => '2026-04-17',
                'tanggal_te' => '2026-04-08',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000002030',
                'nama_barang' => 'Software License',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2026-02-18',
                'tanggal_out' => '2026-05-12',
                'tanggal_te' => '2026-04-16',
                'tanggal_rete' => '2026-05-07',
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000002032',
                'nama_barang' => 'Up Bandwidth On Demand',
                'vendor' => 'PT Telkom Indonesia',
                'tanggal_in' => '2026-02-23',
                'tanggal_out' => '2026-03-06',
                'tanggal_te' => '2026-03-04',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '1000004280',
                'nama_barang' => 'IT Peripheral Storage and Troubleshot',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2026-02-24',
                'tanggal_out' => null,
                'tanggal_te' => null,
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '1000004315',
                'nama_barang' => 'Installation CCTV Explotion Proof',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2026-03-18',
                'tanggal_out' => null,
                'tanggal_te' => null,
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000002052',
                'nama_barang' => 'Additional Storage 200GB',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2026-03-24',
                'tanggal_out' => '2026-04-24',
                'tanggal_te' => '2026-04-23',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000002063',
                'nama_barang' => 'Renewal License AUTOCAD LT 2026',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2026-04-10',
                'tanggal_out' => '2026-04-30',
                'tanggal_te' => '2026-04-24',
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000002091',
                'nama_barang' => 'Renewal for Mail Security',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2026-04-28',
                'tanggal_out' => null,
                'tanggal_te' => null,
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '1000004410',
                'nama_barang' => 'Notebook for SM,SNM, and DM',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2026-05-06',
                'tanggal_out' => null,
                'tanggal_te' => null,
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '4000002121',
                'nama_barang' => 'Renewal License Bandwidth Management BTG-JKT Office',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2026-05-11',
                'tanggal_out' => null,
                'tanggal_te' => null,
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
            [
                'kode_pengadaan' => '1000004454',
                'nama_barang' => 'Windows 11 Pro Volume GGWA',
                'vendor' => 'Vendor Default',
                'tanggal_in' => '2026-05-15',
                'tanggal_out' => null,
                'tanggal_te' => null,
                'tanggal_rete' => null,
                'tanggal_po' => null,
            ],
        ];

        foreach ($procurements as $data) {
            Procurement::create($data);
        }
    }
}
