<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Procurement;

class ProcurementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'no' => '1',
                'rp_number' => '1000003892',
                'description' => 'IT Peripheral',
                'date_created' => 'Wednesday, April 23, 2025',
                'send_for_approval_general_director' => 'Wednesday, April 23, 2025',
                'buyer' => 'SU',
                'te_in' => 'Tuesday, May 27, 2025',
                'te_out' => 'Tuesday, May 27, 2025',
                're_te' => null,
                'po' => 'Monday, June 16, 2025',
                'vendor' => 'PT Alpha Cipta',
                'delivery' => 'Tuesday, July 15, 2025',
                'so' => null,
                'qc' => 'Monday, July 7, 2025',
                'rr' => 'Monday, July 7, 2025',
                'status' => 'PO'
            ],
            [
                'no' => '2',
                'rp_number' => '1000003895',
                'description' => 'Asus zen book for SM',
                'date_created' => 'Wednesday, April 23, 2025',
                'send_for_approval_general_director' => 'Wednesday, April 23, 2025',
                'buyer' => 'SU',
                'te_in' => 'Monday, May 19, 2025',
                'te_out' => 'Wednesday, May 21, 2025',
                're_te' => 'Tuesday, May 27, 2025',
                'po' => 'Monday, June 16, 2025',
                'vendor' => 'PT Technology Solustion Indo',
                'delivery' => 'Thursday, July 17, 2025',
                'so' => null,
                'qc' => null,
                'rr' => 'Monday, July 21, 2025',
                'status' => 'PO'
            ],
            [
                'no' => '3',
                'rp_number' => '1000003896',
                'description' => 'Microsoft Surface for DPGM',
                'date_created' => 'Wednesday, April 23, 2025',
                'send_for_approval_general_director' => 'Wednesday, April 23, 2025',
                'buyer' => null,
                'te_in' => 'Monday, May 19, 2025',
                'te_out' => 'Wednesday, May 21, 2025',
                're_te' => 'Monday, May 26, 2025 / Tuesday, May 27, 2025',
                'po' => 'Monday, June 16, 2025',
                'vendor' => 'PT Alpha Cipta',
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'PO'
            ],
            [
                'no' => '4',
                'rp_number' => '4000001763',
                'description' => 'Renewal Autocad',
                'date_created' => 'Wednesday, April 16, 2025',
                'send_for_approval_general_director' => 'Wednesday, April 16, 2025',
                'buyer' => null,
                'te_in' => 'Thursday, May 22, 2025',
                'te_out' => 'Monday, May 26, 2025',
                're_te' => null,
                'po' => 'Monday, June 16, 2025',
                'vendor' => 'PT Pacific Citra Mandiri',
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'PO'
            ],
            [
                'no' => '5',
                'rp_number' => '1000003915',
                'description' => 'Microsoft Surface for COMUT',
                'date_created' => 'Thursday, May 8, 2025',
                'send_for_approval_general_director' => 'Monday, May 19, 2025',
                'buyer' => null,
                'te_in' => 'Friday, May 23, 2025',
                'te_out' => 'Friday, May 23, 2025',
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => 'Monday, May 26, 2025',
                'so' => 'Monday, May 26, 2025',
                'qc' => null,
                'rr' => null,
                'status' => 'PO'
            ],
            [
                'no' => '6',
                'rp_number' => '4000001812',
                'description' => 'Windows 11 Pro Volume GGWA',
                'date_created' => 'Wednesday, May 21, 2025',
                'send_for_approval_general_director' => 'Monday, May 26, 2025',
                'buyer' => null,
                'te_in' => 'Tuesday, July 1, 2025',
                'te_out' => 'Wednesday, July 2, 2025',
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'TE'
            ],
            [
                'no' => '7',
                'rp_number' => '4000001815',
                'description' => 'Sectigo SSL 1 Year and Installation',
                'date_created' => 'Friday, May 23, 2025',
                'send_for_approval_general_director' => 'Monday, May 26, 2025',
                'buyer' => null,
                'te_in' => 'Monday, May 26, 2025',
                'te_out' => 'Monday, May 26, 2025',
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'TE'
            ],
            [
                'no' => '8',
                'rp_number' => '1000003941',
                'description' => 'Installation CCTV ExploProof and Indoor',
                'date_created' => 'Tuesday, May 27, 2025',
                'send_for_approval_general_director' => 'Tuesday, May 27, 2025',
                'buyer' => null,
                'te_in' => 'Monday, June 23, 2025',
                'te_out' => 'Tuesday, June 24, 2025',
                're_te' => 'Monday, July 21, 2025',
                'po' => '25 Agustus 2025',
                'vendor' => 'CV Tigatra Adikara',
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'PO'
            ],
            [
                'no' => '9',
                'rp_number' => '4000001822',
                'description' => 'Client Cert for SSL VPN',
                'date_created' => 'Wednesday, May 28, 2025',
                'send_for_approval_general_director' => 'Friday, May 30, 2025',
                'buyer' => null,
                'te_in' => null,
                'te_out' => null,
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => 'Monday, June 9, 2025',
                'qc' => null,
                'rr' => null,
                'status' => 'PO'
            ],
            [
                'no' => '10',
                'rp_number' => '4000001762',
                'description' => '1 Year Renewal Baracuda',
                'date_created' => 'Wednesday, April 16, 2025',
                'send_for_approval_general_director' => 'Wednesday, April 16, 2025',
                'buyer' => null,
                'te_in' => null,
                'te_out' => null,
                're_te' => 'Friday, May 30, 2025',
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'RE-TE'
            ],
            [
                'no' => '11',
                'rp_number' => '4000001824',
                'description' => 'Renewal Microsoft 365 Business',
                'date_created' => 'Monday, June 2, 2025',
                'send_for_approval_general_director' => 'Tuesday, June 3, 2025',
                'buyer' => null,
                'te_in' => 'Tuesday, July 1, 2025',
                'te_out' => 'Wednesday, July 2, 2025',
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'TE'
            ],
            [
                'no' => '12',
                'rp_number' => '4000001832',
                'description' => 'Renewal License Cisco Catalyst 9200L-48T',
                'date_created' => 'Monday, June 9, 2025',
                'send_for_approval_general_director' => 'Thursday, June 12, 2025',
                'buyer' => null,
                'te_in' => 'Monday, June 23, 2025',
                'te_out' => 'Wednesday, June 25, 2025',
                're_te' => null,
                'po' => null,
                'vendor' => 'PT KDDI Indonesia',
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'TE'
            ],
            [
                'no' => '13',
                'rp_number' => '4000001835',
                'description' => 'Renewal License Fortigate Bontang-Jakarta',
                'date_created' => 'Tuesday, June 10, 2025',
                'send_for_approval_general_director' => null,
                'buyer' => null,
                'te_in' => 'Monday, June 23, 2025',
                'te_out' => 'Wednesday, June 25, 2025',
                're_te' => 'Monday, July 7, 2025',
                'po' => null,
                'vendor' => 'PT KDDI Indonesia',
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'RE-TE'
            ],
            [
                'no' => '14',
                'rp_number' => '4000001842',
                'description' => 'Maintenance & Update Core Website and CMS',
                'date_created' => 'Wednesday, June 18, 2025',
                'send_for_approval_general_director' => 'Thursday, June 19, 2025',
                'buyer' => null,
                'te_in' => 'Friday, July 11, 2025',
                'te_out' => 'Tuesday, July 29, 2025',
                're_te' => 'Wednesday, August 20, 2025',
                'po' => null,
                'vendor' => 'PT Go Online Solusi',
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'RE-TE'
            ],
            [
                'no' => '15',
                'rp_number' => '4000001834',
                'description' => 'ISP ASTINET - WISTA',
                'date_created' => 'Tuesday, June 10, 2025',
                'send_for_approval_general_director' => 'Friday, June 13, 2025',
                'buyer' => null,
                'te_in' => 'Monday, June 30, 2025',
                'te_out' => 'Tuesday, July 1, 2025',
                're_te' => null,
                'po' => null,
                'vendor' => 'PT Telkom Indonesia',
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'TE'
            ],
            [
                'no' => '16',
                'rp_number' => '4000001849',
                'description' => 'Renewal Microsoft Teams Pro Jakarta Office',
                'date_created' => 'Thursday, July 3, 2025',
                'send_for_approval_general_director' => 'Thursday, July 3, 2025',
                'buyer' => null,
                'te_in' => null,
                'te_out' => 'Monday, July 7, 2025',
                're_te' => null,
                'po' => null,
                'vendor' => 'PT KDDI Indonesia',
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'TE'
            ],
            [
                'no' => '17',
                'rp_number' => '1000003943',
                'description' => 'Access Control for Administration Building',
                'date_created' => 'Wednesday, May 28, 2025',
                'send_for_approval_general_director' => 'Friday, July 4, 2025',
                'buyer' => 'Thursday, September 11, 2025',
                'te_in' => null,
                'te_out' => 'Thursday, September 18, 2025',
                're_te' => 'Thursday, November 28 2025 / Wednesday, December 3, 2025',
                'po' => null,
                'vendor' => 'CV Tigatra Adikara',
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => 'Wednesday, 4 Januari 2026',
                'status' => 'PO'
            ],
            [
                'no' => '18',
                'rp_number' => '1000004001',
                'description' => 'Printer-Scanner Peripheral',
                'date_created' => 'Tuesday, July 22, 2025',
                'send_for_approval_general_director' => 'Thursday, July 24, 2025',
                'buyer' => 'Wednesday, August 13, 2025',
                'te_in' => null,
                'te_out' => 'Thursday, August 14, 2025',
                're_te' => null,
                'po' => '20 agustus 2025',
                'vendor' => 'PT Technology Solustion Indo',
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => 'Monday, 22 September 2025',
                'status' => 'PO'
            ],
            [
                'no' => '19',
                'rp_number' => '1000004005',
                'description' => 'IT Peripheral',
                'date_created' => 'Wednesday, July 23, 2025',
                'send_for_approval_general_director' => 'Tuesday, July 29, 2025',
                'buyer' => null,
                'te_in' => 'Tuesday, August 19, 2025',
                'te_out' => 'Wednesday, August 20, 2025',
                're_te' => null,
                'po' => '28 agustus 2025',
                'vendor' => 'PT Alpha Cipta',
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => 'Monday, 22 September 2025',
                'status' => 'PO'
            ],
            [
                'no' => '20',
                'rp_number' => '1000004003',
                'description' => 'Visio dan Project License',
                'date_created' => 'Tuesday, July 29, 2025',
                'send_for_approval_general_director' => 'Tuesday, July 29, 2025',
                'buyer' => null,
                'te_in' => 'Tuesday, August 19, 2025',
                'te_out' => 'Wednesday, August 20, 2025',
                're_te' => null,
                'po' => '4500004167',
                'vendor' => 'PT Alpha Cipta Computindo',
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => 'Monday, 17 November 2025',
                'status' => 'PO'
            ],
            [
                'no' => '21',
                'rp_number' => '4000001898',
                'description' => 'Microsoft Power BI Premium',
                'date_created' => 'Wednesday, September 17, 2025',
                'send_for_approval_general_director' => 'Thursday, September 18, 2025',
                'buyer' => 'Wednesday, September 24, 2025',
                'te_in' => null,
                'te_out' => 'Wednesday, September 24, 2025',
                're_te' => null,
                'po' => null,
                'vendor' => 'PT Logos Teknologi Utama',
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'TE'
            ],
            [
                'no' => '22',
                'rp_number' => '1000004062',
                'description' => 'Replace & Install SASHDD 02&05 Dell ME4024',
                'date_created' => 'Thursday, September 18, 2025',
                'send_for_approval_general_director' => 'Monday, September 22, 2025',
                'buyer' => 'Thursday, October 16, 2025',
                'te_in' => null,
                'te_out' => 'Friday, October 17, 2025',
                're_te' => null,
                'po' => null,
                'vendor' => 'PT KDDI Indonesia',
                'delivery' => null,
                'so' => '4500004148',
                'qc' => null,
                'rr' => null,
                'status' => 'PO'
            ],
            [
                'no' => '23',
                'rp_number' => '4000001901',
                'description' => 'Renewal License and Maintenance JKT Office',
                'date_created' => 'Friday, September 19, 2025',
                'send_for_approval_general_director' => 'Monday, September 22, 2025',
                'buyer' => null,
                'te_in' => 'Monday, October 27, 2025',
                'te_out' => 'Tuesday, October 28, 2025',
                're_te' => 'Thursday, Desember 4, 2025 / Monday, December 8, 2025',
                'po' => null,
                'vendor' => 'PT KDDI Indonesia',
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'RE-TE'
            ],
            [
                'no' => '24',
                'rp_number' => '4000001910',
                'description' => 'Annual Maintenance Fortigate JKT and BTG',
                'date_created' => 'Monday, September 22, 2025',
                'send_for_approval_general_director' => 'Monday, September 22, 2025',
                'buyer' => 'Thursday, October 2, 2025',
                'te_in' => null,
                'te_out' => 'Thursday, October 2 2025',
                're_te' => null,
                'po' => null,
                'vendor' => 'PT Alpha Cipta',
                'delivery' => null,
                'so' => 'Tuesday, October 14 , 2025',
                'qc' => null,
                'rr' => null,
                'status' => 'PO'
            ],
            [
                'no' => '25',
                'rp_number' => '1000004102',
                'description' => 'ID Card Printer for Personnel',
                'date_created' => 'Monday, October 20, 2025',
                'send_for_approval_general_director' => 'Friday, October 24, 2025',
                'buyer' => 'Thursday, November 13, 2025',
                'te_in' => null,
                'te_out' => 'Thursday, November 13, 2025',
                're_te' => null,
                'po' => 'Wednesday, 10 Desember 2025',
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'PO'
            ],
            [
                'no' => '26',
                'rp_number' => '1000004114',
                'description' => 'Notebook Microsoft Surface Pro for PGM',
                'date_created' => 'Wednesday, November 5, 2025',
                'send_for_approval_general_director' => 'Wednesday, November 5, 2025',
                'buyer' => 'Monday, November 17, 2025',
                'te_in' => null,
                'te_out' => 'Friday, November 21, 2025',
                're_te' => null,
                'po' => '4500004227',
                'vendor' => 'PT Alpha Cipta Computindo',
                'delivery' => null,
                'so' => '4500004227',
                'qc' => null,
                'rr' => null,
                'status' => 'PO'
            ],
            [
                'no' => '27',
                'rp_number' => '4000001936',
                'description' => 'Renewal License Nextset SSO Browser',
                'date_created' => 'Wednesday, November 5, 2025',
                'send_for_approval_general_director' => 'Thursday, November 6, 2025',
                'buyer' => 'Tuesday, November 25, 2025',
                'te_in' => null,
                'te_out' => 'Tuesday, Desember 2, 2025',
                're_te' => 'Friday, Desember 5, 2025 / Monday, December 8, 2025',
                'po' => null,
                'vendor' => 'PT KDDI Indonesia',
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'RE-TE'
            ],
            [
                'no' => '28',
                'rp_number' => '4000001959',
                'description' => 'Renewal 1Y VMWare and Veeam License',
                'date_created' => 'Monday, Desember 1, 2025',
                'send_for_approval_general_director' => 'Monday, Desember 8, 2025',
                'buyer' => null,
                'te_in' => 'Monday, Januari 5, 2026',
                'te_out' => null,
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'TE'
            ],
            [
                'no' => '29',
                'rp_number' => '4000001961',
                'description' => 'Renewal License Cisco Catalyst 9200L-48T',
                'date_created' => 'Tuesday, Desember 9, 2025',
                'send_for_approval_general_director' => 'Tuesday, Desember 9, 2025',
                'buyer' => 'Thursday, Januari 29, 2026',
                'te_in' => null,
                'te_out' => 'Thursday, Januari 5, 2026',
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'TE'
            ],
            [
                'no' => '30',
                'rp_number' => '1000004154',
                'description' => 'IT Peripheral',
                'date_created' => 'Tuesday, Desember 9, 2025',
                'send_for_approval_general_director' => 'Wednesday, Desember 18, 2025',
                'buyer' => 'Thursday, Januari 8, 2026',
                'te_in' => null,
                'te_out' => 'Wednesday, Januari 14, 2026',
                're_te' => 'Monday, Januari 19, 2026 / Tuesday, Januari 20, 2026',
                'po' => '4500004270',
                'vendor' => 'CV Tigatra Adikara',
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'PO'
            ],
            [
                'no' => '31',
                'rp_number' => '1000004178',
                'description' => 'PC Replacement for JKT Staff',
                'date_created' => 'Wednesday, Desember 24, 2025',
                'send_for_approval_general_director' => 'Monday, Desember 29, 2025',
                'buyer' => 'Wednesday, Januari 14, 2026',
                'te_in' => null,
                'te_out' => 'Thursday, Januari 15, 2026',
                're_te' => null,
                'po' => '4500004265',
                'vendor' => 'CV Tigatra Adikara',
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => 'Monday, 2 February 2026',
                'status' => 'PO'
            ],
            [
                'no' => '32',
                'rp_number' => '1000004175',
                'description' => 'IT Peripheral',
                'date_created' => 'Tuesday, Desember 23, 2025',
                'send_for_approval_general_director' => 'Friday, Januari 9, 2025',
                'buyer' => 'Thursday, Januari 29, 2026',
                'te_in' => null,
                'te_out' => 'Friday, Januari 30, 2026',
                're_te' => null,
                'po' => '4500004275',
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => 'Monday, 23 February 2026',
                'status' => 'PO'
            ],
            [
                'no' => '33',
                'rp_number' => '4000001973',
                'description' => 'License Acronis JKT and Cisco BTG',
                'date_created' => 'Thursday, Januari 8, 2026',
                'send_for_approval_general_director' => 'Friday, Januari 9, 2025',
                'buyer' => 'Wednesday, February 25, 2026',
                'te_in' => null,
                'te_out' => 'Monday, Maret 2, 2026',
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => '5000001309',
                'qc' => null,
                'rr' => null,
                'status' => 'PO'
            ],
            [
                'no' => '34',
                'rp_number' => '4000001988',
                'description' => 'Migration on-premise server to cloud',
                'date_created' => 'Wednesday, Januari 21, 2026',
                'send_for_approval_general_director' => 'Thursday, Januari 22, 2025',
                'buyer' => 'Tuesday, Januari 3, 2026',
                'te_in' => null,
                'te_out' => 'Friday, Januari 6, 2025',
                're_te' => 'Monday, Januari 9, 2026',
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => '5000001279',
                'qc' => null,
                'rr' => null,
                'status' => 'PO'
            ],
            [
                'no' => '35',
                'rp_number' => '4000002004',
                'description' => 'MFA License for AD Server',
                'date_created' => 'Friday, Januari 30, 2026',
                'send_for_approval_general_director' => 'Friday, Januari 30, 2026',
                'buyer' => 'Tuesday. February 24, 2026',
                'te_in' => null,
                'te_out' => 'Wednesday, February 25, 2026',
                're_te' => null,
                'po' => null,
                'vendor' => 'PT KDDI Indonesia',
                'delivery' => null,
                'so' => '5000001289',
                'qc' => null,
                'rr' => null,
                'status' => 'PO'
            ],
            [
                'no' => '36',
                'rp_number' => '4000002010',
                'description' => 'FO PKT-KMI 3 core',
                'date_created' => 'Thursday, Januari 5, 2026',
                'send_for_approval_general_director' => 'Friday, Januari 6, 2026',
                'buyer' => null,
                'te_in' => 'Thursday, April 2, 2026',
                'te_out' => 'Tuesday, April 7, 2026',
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'TE'
            ],
            [
                'no' => '37',
                'rp_number' => '4000002018',
                'description' => 'Dual Service Connectivity 100Mbps & Public 200Mbps',
                'date_created' => 'Wednesday, Januari 11, 2026',
                'send_for_approval_general_director' => 'Thursday, Januari 12, 2026',
                'buyer' => null,
                'te_in' => 'Friday, Maret 6, 2026',
                'te_out' => 'Wednesday, Maret 11, 2026',
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'TE'
            ],
            [
                'no' => '38',
                'rp_number' => '4000002017',
                'description' => 'Project FO Link to 7 location CCTV',
                'date_created' => 'Tuesday, Januari 10, 2026',
                'send_for_approval_general_director' => 'Thursday, Januari 12, 2026',
                'buyer' => 'Wednesday, April 8, 2026',
                'te_in' => null,
                'te_out' => 'Friday, April 17, 2026',
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'TE'
            ],
            [
                'no' => '39',
                'rp_number' => '4000002030',
                'description' => 'Software License',
                'date_created' => 'Wednesday, February 18, 2026',
                'send_for_approval_general_director' => 'Monday, February 23, 2026',
                'buyer' => null,
                'te_in' => 'Thursday, April 16, 2026',
                'te_out' => 'Thursday, April 16, 2026',
                're_te' => 'Thursday, Mei 7, 2026 / Monday, Mei 12, 2026',
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'RE-TE'
            ],
            [
                'no' => '40',
                'rp_number' => '4000002032',
                'description' => 'Up Bandwidth On Demand',
                'date_created' => 'Monday, February 23, 2026',
                'send_for_approval_general_director' => 'Monday, February 23, 2026',
                'buyer' => 'Wednesday, Maret 4, 2026',
                'te_in' => null,
                'te_out' => 'Friday, Maret 6, 2026',
                're_te' => null,
                'po' => null,
                'vendor' => 'PT Telkom Indonesia',
                'delivery' => null,
                'so' => '5000001303',
                'qc' => null,
                'rr' => null,
                'status' => 'PO'
            ],
            [
                'no' => '41',
                'rp_number' => '1000004280',
                'description' => 'IT Peripheral Storage and Troubleshot',
                'date_created' => 'Tuesday, February 24, 2026',
                'send_for_approval_general_director' => 'Thursday, Maret 5, 2026',
                'buyer' => null,
                'te_in' => null,
                'te_out' => null,
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'RP'
            ],
            [
                'no' => '42',
                'rp_number' => '1000004315',
                'description' => 'Installation CCTV Explotion Proof',
                'date_created' => 'Wednesday, Maret 18, 2026',
                'send_for_approval_general_director' => 'Wednesday, Maret 18, 2026',
                'buyer' => null,
                'te_in' => null,
                'te_out' => null,
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'RP'
            ],
            [
                'no' => '43',
                'rp_number' => '4000002052',
                'description' => 'Additional Storage 200GB',
                'date_created' => 'Tuesday, Maret 24, 2026',
                'send_for_approval_general_director' => 'Wednesday, Maret 30, 2026',
                'buyer' => null,
                'te_in' => 'Thursday, April 23, 2026',
                'te_out' => 'Thursday, April 24, 2026',
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'TE'
            ],
            [
                'no' => '44',
                'rp_number' => '4000002063',
                'description' => 'Renewal License AUTOCAD LT 2026',
                'date_created' => 'Friday, April 10, 2026',
                'send_for_approval_general_director' => 'Monday, April 13, 2026',
                'buyer' => null,
                'te_in' => 'Thursday, April 24, 2026',
                'te_out' => 'Thusrday, April 30, 2026',
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'TE'
            ],
            [
                'no' => '45',
                'rp_number' => '4000002091',
                'description' => 'Renewal for Mail Security',
                'date_created' => 'Tuesday, April 28, 2026',
                'send_for_approval_general_director' => 'Thursday, April 30, 2026',
                'buyer' => null,
                'te_in' => null,
                'te_out' => null,
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'RP'
            ],
            [
                'no' => '46',
                'rp_number' => '1000004410',
                'description' => 'Notebook for SM,SNM, and DM',
                'date_created' => 'Wednesday, Mei 6, 2026',
                'send_for_approval_general_director' => 'Monday, Mei 11, 2026',
                'buyer' => null,
                'te_in' => null,
                'te_out' => null,
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'RP'
            ],
            [
                'no' => '47',
                'rp_number' => '4000002121',
                'description' => 'Renewal License Bandwidth Management BTG-JKT Office',
                'date_created' => 'Monday, Mei 11, 2026',
                'send_for_approval_general_director' => 'Monday, Mei 11, 2026',
                'buyer' => null,
                'te_in' => null,
                'te_out' => null,
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'RP'
            ],
            [
                'no' => '48',
                'rp_number' => '1000004454',
                'description' => 'Windows 11 Pro Volume GGWA',
                'date_created' => 'Friday, Mei 15, 2026',
                'send_for_approval_general_director' => 'Tuesday, Mei 19, 2026',
                'buyer' => null,
                'te_in' => null,
                'te_out' => null,
                're_te' => null,
                'po' => null,
                'vendor' => null,
                'delivery' => null,
                'so' => null,
                'qc' => null,
                'rr' => null,
                'status' => 'RP'
            ]
        ];

        foreach ($data as $item) {
            Procurement::updateOrCreate(
                ['rp_number' => $item['rp_number']],
                $item
            );
        }
    }
}
